### ISSUE TITLE
Missing validation using SPARQL query [-5]

### ISSUE THREAD

**Issue by skodapetr** [Sawa-q/datin#3]
See 11.1 Integrity constraints of [The RDF Data Cube Vocabulary](https://www.w3.org/TR/vocab-data-cube/) specification.

**Comment by Sawa-q** [comment]
How many queries do I need to have? There are about 20 on that web, do I need them all?

**Comment by skodapetr** [comment]
All of them, each validate certain aspect of the data cube. They should all pass, or you should comment why the did not.  I would recommend putting the queries into a file / array and just iterate over them and execute them on the data.
